networks:
  default:
    name: todo
services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./docker/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  postgres-data: